#!/bin/bash

if [ -z $CMANGOS_VERSION ]
then
  echo 'You need to specify the $CMANGOS_VERSION environment variable, which is the cmangos/mangos-classic version...see https://github.com/cmangos/mangos-classic/releases'
  exit 1
fi

MANGOS_CONFIG_FILE="/etc/cmangos-classic/mangosd.conf"
AHBOT_CONFIG_FILE="/etc/cmangos-classic/ahbot.conf"
TEMP_DIR="/tmp"
BINARY_PACKAGE="$TEMP_DIR/cmangos-classic-$CMANGOS_VERSION.tar.gz"
BINARY_DIR="/cmangos/bin"
CLIENT_EXTRACTED_FILES_PACKAGE="$TEMP_DIR/1.12.1-client-extracted-files.tar.gz" 

if [ ! -f "./cmangos/bin/mangosd" ]; then
  if [ ! -e $BINARY_PACKAGE ]; then
    echo "$BINARY_PACKAGE missing...this file can be generated using https://github.com/maxc0c0s/cmangos-classic-deploy"
    exit 1
  fi
  if [ ! -e $CLIENT_EXTRACTED_FILES_PACKAGE ]; then
    echo "$CLIENT_EXTRACTED_FILES_PACKAGE missing...The content generated by https://github.com/cmangos/mangos-classic/blob/master/contrib/extractor_binary/ExtractResources.sh must be compressed into $CLIENT_EXTRACTED_FILES_PACKAGE"
    exit 1
  fi

  echo "extracting $BINARY_PACKAGE"
  tar -xf $BINARY_PACKAGE -C /

  echo "extracting $CLIENT_EXTRACTED_FILES_PACKAGE in $BINARY_DIR"
  tar -xf $CLIENT_EXTRACTED_FILES_PACKAGE -C $BINARY_DIR
fi

if [ ! -e $MANGOS_CONFIG_FILE ]; then
  echo "$MANGOS_CONFIG_FILE must be present...a template for this file can be found here: https://github.com/cmangos/mangos-classic/blob/master/src/mangosd/mangosd.conf.dist.in"
  exit 1
fi
if [ ! -e $AHBOT_CONFIG_FILE ]; then
  echo "$AHBOT_CONFIG_FILE must be present...a template for this file can be found here: https://github.com/cmangos/mangos-classic/blob/master/src/game/AuctionHouseBot/ahbot.conf.dist.in"
  exit 1
fi
if [ ! -e $BINARY_DIR/mangosd ]; then
  echo "$BINARY_DIR/mangosd must be present...this file comes from $BINARY_PACKAGE"
  exit 1
fi

# TODO this command could be called from a custom script
/wait-for-it/wait-for-it.sh db-master:3306

if [ -z $@ ]; then
  cd $BINARY_DIR
  ./mangosd -c $MANGOS_CONFIG_FILE -a $AHBOT_CONFIG_FILE
else
  exec $@
fi
